/**********

@Library('es-shared-library')_

// Building the jobParameter map
def Map jobParameter = [
  "myparam_one"	: myparam_one,
  "myparam_two"	: myparam_two
 ]

// Calling the CI Pipeline
methodtester()


/*    parameters {
        string(name: 'myparam_one', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')

        text(name: 'myparam_two', defaultValue: '', description: 'Enter some information about the person')

    }*/


/********/

pipeline {
  parameters {
        string(name: 'myparam_one', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    }
    agent any
    stages {
        stage('Example') {
            steps {
                echo "Hello ${params.myparam_one}"
            }
        }
    }
}
